//! The host compilation of [`super`]'s distribution mathematics.
//!
//! **Generated by `tools/host_twins.py`.** This is the marked region of
//! `univariate.rs` after the edits that script documents, and
//! `distributions_bitexact::host_twin_is_the_same_source` fails if it has drifted.
//! Edit `univariate.rs`, never this.
//!
//! The `use` lines are the one thing that differs beyond those edits: they aim
//! `rng` and `special` at the host twins, so the shared source resolves to host
//! functions here and to device ones there.

#![allow(
    clippy::excessive_precision,
    unused_assignments,
    unused_parens,
    unused_variables
)]

// A glob for the same reason as in `special_host.rs`; the two explicit `use` lines
// that follow shadow it, which is what points `rng` and `special` at the host twins.
use super::rng::host as rng;
use super::special::host as special;
#[allow(unused_imports)]
use super::*;

// >>> shared

/// The log-density (or log-mass) of `kind` at `x`.
pub fn log_prob_of(x: f32, a: f32, b: f32, c: f32, nf: NonFinite, kind: u32) -> f32 {
    let mut out: f32 = 0.0;
    if (kind == 0) {
        // Normal(loc = a, scale = b).
        let z = (x - a) / b;
        out = -0.5f32 * z * z - f32::ln(b) - special::HALF_LN_2PI;
    } else if (kind == 1) {
        // Uniform(low = a, high = b): flat inside, impossible outside.
        out = -nf.inf;
        if x >= a && x < b {
            out = -f32::ln(b - a);
        }
    } else if (kind == 2) {
        // Exponential(rate = a).
        out = f32::ln(a) - a * x;
    } else if (kind == 3) {
        // Laplace(loc = a, scale = b).
        out = -f32::ln(2.0f32 * b) - f32::abs(x - a) / b;
    } else if (kind == 4) {
        // Cauchy(loc = a, scale = b).
        let z = (x - a) / b;
        out = -f32::ln(special::PI) - f32::ln(b) - special::log1p_f32(z * z);
    } else if (kind == 5) {
        // Gumbel(loc = a, scale = b).
        let z = (x - a) / b;
        out = -(z + f32::exp(-z)) - f32::ln(b);
    } else if (kind == 6) {
        // HalfNormal(scale = a): the Gaussian folded at zero, so twice the density.
        let z = x / a;
        out = -nf.inf;
        if x >= 0.0f32 {
            out = -0.5f32 * z * z - f32::ln(a) - special::HALF_LN_2PI + special::LN_2;
        }
    } else if (kind == 7) {
        // HalfCauchy(scale = a).
        let z = x / a;
        out = -nf.inf;
        if x >= 0.0f32 {
            out = special::LN_2 - f32::ln(special::PI) - f32::ln(a) - special::log1p_f32(z * z);
        }
    } else if (kind == 8) {
        // LogNormal(loc = a, scale = b): a Normal in ln x, minus the Jacobian.
        let l = f32::ln(x);
        let z = (l - a) / b;
        out = -0.5f32 * z * z - f32::ln(b) - special::HALF_LN_2PI - l;
    } else if (kind == 9) {
        // Pareto(scale = a, alpha = b).
        out = f32::ln(b) + b * f32::ln(a) - (b + 1.0f32) * f32::ln(x);
    } else if (kind == 10) {
        // Weibull(scale = a, concentration = b).
        let z = x / a;
        out = f32::ln(b) - f32::ln(a) + (b - 1.0f32) * f32::ln(z) - f32::powf(z, b);
    } else if (kind == 11) {
        // Kumaraswamy(a, b): a Beta-shaped density whose CDF is elementary.
        let xa = f32::powf(x, a);
        out = f32::ln(a)
            + f32::ln(b)
            + (a - 1.0f32) * f32::ln(x)
            + special::xlog1py_f32(b - 1.0f32, -xa);
    } else if (kind == 12) {
        // Gamma(concentration = a, rate = b).
        out = special::xlogy_f32(a, b) + (a - 1.0f32) * f32::ln(x) - b * x - special::lgamma_f32(a);
    } else if (kind == 13) {
        // InverseGamma(concentration = a, rate = b).
        out = a * f32::ln(b) - special::lgamma_f32(a) - (a + 1.0f32) * f32::ln(x) - b / x;
    } else if (kind == 14) {
        // Beta(concentration1 = a, concentration0 = b).
        out = special::xlogy_f32(a - 1.0f32, x) + special::xlog1py_f32(b - 1.0f32, -x)
            - special::lbeta_f32(a, b);
    } else if (kind == 15) {
        // StudentT(df = a, loc = b, scale = c).
        let z = (x - b) / c;
        let half = 0.5f32 * a;
        out = special::lgamma_f32(half + 0.5f32)
            - special::lgamma_f32(half)
            - 0.5f32 * f32::ln(a * special::PI)
            - f32::ln(c)
            - (half + 0.5f32) * special::log1p_f32(z * z / a);
    } else if (kind == 16) {
        // FisherSnedecor(df1 = a, df2 = b), spelled as PyTorch spells it.
        let h1 = 0.5f32 * a;
        let h2 = 0.5f32 * b;
        let ratio = a / b;
        out = special::lgamma_f32(h1 + h2) - special::lgamma_f32(h1) - special::lgamma_f32(h2)
            + h1 * f32::ln(ratio)
            + (h1 - 1.0f32) * f32::ln(x)
            - (h1 + h2) * special::log1p_f32(ratio * x);
    } else if (kind == 17) {
        // VonMises(loc = a, concentration = b).
        out = b * f32::cos(x - a) - f32::ln(2.0f32 * special::PI) - special::log_i0_f32(b);
    } else if (kind == 18) {
        // ContinuousBernoulli(logits = a) on [0, 1].
        out = x * a - special::softplus_f32(a) + cont_bernoulli_log_norm(a);
    } else if (kind == 19) {
        // Bernoulli(logits = a): `x·logit − softplus(logit)`, which is the negative
        // binary cross entropy and is finite at every logit, unlike `x ln p`.
        out = x * a - special::softplus_f32(a);
    } else if (kind == 20) {
        // Geometric(logits = a), counting failures before the first success.
        out = x * special::log_sigmoid_f32(-a) + special::log_sigmoid_f32(a);
    } else if (kind == 21) {
        // Poisson(rate = a).
        out = special::xlogy_f32(x, a) - a - special::lgamma_f32(x + 1.0f32);
    } else if (kind == 22) {
        // Binomial(total_count = a, logits = b).
        out = special::log_binom_f32(a, x) + x * b - a * special::softplus_f32(b);
    } else if (kind == 23) {
        // NegativeBinomial(total_count = a, logits = b).
        out = a * special::log_sigmoid_f32(-b)
            + x * special::log_sigmoid_f32(b)
            + special::lgamma_f32(a + x)
            - special::lgamma_f32(1.0f32 + x)
            - special::lgamma_f32(a);
    } else if (kind == 24) {
        // LogitRelaxedBernoulli(temperature = a, logits = b).
        let diff = b - x * a;
        out = f32::ln(a) + diff - 2.0f32 * special::softplus_f32(diff);
    } else if (kind == 25) {
        // RelaxedBernoulli(temperature = a, logits = b): the logit-relaxed density
        // pushed through a sigmoid, so `x = σ(y)` and `dy/dx = 1/(x(1−x))`.
        let y = f32::ln(x) - special::log1p_f32(-x);
        let diff = b - y * a;
        out = f32::ln(a) + diff
            - 2.0f32 * special::softplus_f32(diff)
            - f32::ln(x)
            - special::log1p_f32(-x);
    }
    out
}

/// The mean of a continuous Bernoulli with natural parameter (logit) `t`.
///
/// Its own function because two callers need it: [`moment_of()`] and the score in
/// [`log_prob_grad_of()`], which is the value minus this mean.
pub fn cont_bernoulli_mean(t: f32) -> f32 {
    let mut out: f32 = 0.0;
    if f32::abs(t) > 0.02f32 {
        out = 1.0f32 / (-special::expm1_f32(-t)) - 1.0f32 / t;
    } else {
        out = 0.5f32 + t * (1.0f32 / 12.0f32 - t * t / 720.0f32);
    }
    out
}

/// `ln C(λ)`, the normaliser of a continuous Bernoulli with logit `t`.
///
/// `C(λ) = 2 tanh⁻¹(1 − 2λ)/(1 − 2λ)` has a removable singularity at `λ = ½`, where
/// both halves vanish; away from it the closed form is stable, and within a
/// thousandth of it the fourth-order Taylor series is better than the cancellation
/// would be. The switch is PyTorch's, and so is the series.
pub fn cont_bernoulli_log_norm(logits: f32) -> f32 {
    let p = 1.0f32 / (1.0f32 + f32::exp(-logits));
    let d = p - 0.5f32;
    let mut out: f32 = 0.0;
    if f32::abs(d) > 1.0e-3f32 {
        out = f32::ln(f32::abs(f32::ln(1.0f32 - p) - f32::ln(p)))
            - f32::ln(f32::abs(1.0f32 - 2.0f32 * p));
    } else {
        let d2 = d * d;
        out = special::LN_2 + (4.0f32 / 3.0f32 + 104.0f32 / 45.0f32 * d2) * d2;
    }
    out
}

/// The regularized lower incomplete gamma function `P(a, x)`.
///
/// Numerical Recipes' pairing: the ascending series where it converges quickly
/// (`x < a + 1`) and Lentz's continued fraction for the complement everywhere else.
/// Neither converges well in the other's half, which is why both are here.
///
/// This is the only place a distribution CDF needs an iteration rather than a
/// formula, and it is what makes [`Kind::Gamma`], [`Kind::InverseGamma`] and
/// [`Kind::Poisson`] answerable at all.
pub fn gammainc_p(a: f32, x: f32) -> f32 {
    let mut out: f32 = 0.0;
    if x > 0.0f32 {
        // The factor both branches share, formed in the log so that a large `a`
        // does not overflow on the way to a result in `[0, 1]`.
        let scale = f32::exp(a * f32::ln(x) - x - special::lgamma_f32(a));
        if x < a + 1.0f32 {
            let mut term = 1.0f32 / a;
            let mut sum = term;
            let mut n: u32 = 1;
            while n < 300u32 {
                term = term * x / (a + n as f32);
                sum += term;
                if f32::abs(term) < f32::abs(sum) * 1.0e-8f32 {
                    n = 300u32;
                } else {
                    n += 1u32;
                }
            }
            out = sum * scale;
        } else {
            // Lentz's algorithm for the continued fraction of the upper tail. The
            // two `tiny` guards write into locals rather than straight into `dj`
            // and `cj`: an `if` without an `else` that assigns to a variable the
            // loop carries is the one shape CubeCL's CPU backend miscompiles, and
            // it does so silently.
            let tiny = 1.0e-30f32;
            let mut bj = x + 1.0f32 - a;
            let mut cj = 1.0e30f32;
            let mut dj = 1.0f32 / bj;
            let mut h = dj;
            let mut i: u32 = 1;
            while i < 300u32 {
                let fi = i as f32;
                let an = fi * (a - fi);
                bj += 2.0f32;
                let mut den = an * dj + bj;
                if f32::abs(den) < tiny {
                    den = tiny;
                }
                let mut num = bj + an / cj;
                if f32::abs(num) < tiny {
                    num = tiny;
                }
                cj = num;
                dj = 1.0f32 / den;
                let delta = dj * cj;
                h *= delta;
                if f32::abs(delta - 1.0f32) < 1.0e-8f32 {
                    i = 300u32;
                } else {
                    i += 1u32;
                }
            }
            out = 1.0f32 - scale * h;
        }
    }
    out
}

/// The cumulative distribution function of `kind` at `x`.
///
/// `NaN` where the distribution has no closed-form CDF; the host layer refuses those
/// before it ever launches, so the value is never observed.
pub fn cdf_of(x: f32, a: f32, b: f32, c: f32, nf: NonFinite, kind: u32) -> f32 {
    let mut out: f32 = 0.0;
    out = nf.nan;
    if (kind == 0) {
        out = special::std_normal_cdf_f32((x - a) / b);
    } else if (kind == 1) {
        out = ((x - a) / (b - a)).clamp(0.0f32, 1.0f32);
    } else if (kind == 2) {
        out = -special::expm1_f32(-a * x);
    } else if (kind == 3) {
        // Laplace: written with `expm1` on the shared exponential tail so that the
        // near half of the distribution does not cancel against the leading half.
        let z = (x - a) / b;
        out = 0.5f32 - 0.5f32 * special::sign_f32(z) * special::expm1_f32(-f32::abs(z));
    } else if (kind == 4) {
        out = f32::atan((x - a) / b) / special::PI + 0.5f32;
    } else if (kind == 5) {
        out = f32::exp(-f32::exp(-(x - a) / b));
    } else if (kind == 6) {
        out = 0.0f32;
        if x > 0.0f32 {
            out = special::erf_f32(x / (a * special::SQRT_2));
        }
    } else if (kind == 7) {
        out = 0.0f32;
        if x > 0.0f32 {
            out = 2.0f32 / special::PI * f32::atan(x / a);
        }
    } else if (kind == 8) {
        out = 0.0f32;
        if x > 0.0f32 {
            out = special::std_normal_cdf_f32((f32::ln(x) - a) / b);
        }
    } else if (kind == 9) {
        out = 0.0f32;
        if x > a {
            out = -special::expm1_f32(b * (f32::ln(a) - f32::ln(x)));
        }
    } else if (kind == 10) {
        out = 0.0f32;
        if x > 0.0f32 {
            out = -special::expm1_f32(-f32::powf(x / a, b));
        }
    } else if (kind == 11) {
        out = 0.0f32;
        if x > 0.0f32 {
            out = -special::expm1_f32(b * special::log1p_f32(-f32::powf(x, a)));
        }
    } else if (kind == 12) {
        out = gammainc_p(a, b * x);
    } else if (kind == 13) {
        // 1/X with X ~ Gamma, so the CDF is the Gamma's upper tail at `rate/x`.
        out = 0.0f32;
        if x > 0.0f32 {
            out = 1.0f32 - gammainc_p(a, b / x);
        }
    } else if (kind == 18) {
        // ContinuousBernoulli, PyTorch's closed form, clamped to the unit interval.
        let p = 1.0f32 / (1.0f32 + f32::exp(-a));
        let t = x.clamp(0.0f32, 1.0f32);
        let mut v = t;
        if f32::abs(p - 0.5f32) > 1.0e-3f32 {
            v = (f32::powf(p, t) * f32::powf(1.0f32 - p, 1.0f32 - t) + p - 1.0f32)
                / (2.0f32 * p - 1.0f32);
        }
        out = v.clamp(0.0f32, 1.0f32);
    } else if (kind == 19) {
        // Bernoulli. PyTorch leaves this unimplemented; it is two lines and a step
        // function is a perfectly good CDF.
        out = 1.0f32;
        if x < 0.0f32 {
            out = 0.0f32;
        } else if x < 1.0f32 {
            out = 1.0f32 / (1.0f32 + f32::exp(a));
        }
    } else if (kind == 20) {
        // Geometric: `1 − (1−p)^(⌊x⌋+1)`.
        out = 0.0f32;
        if x >= 0.0f32 {
            out = -special::expm1_f32((f32::floor(x) + 1.0f32) * special::log_sigmoid_f32(-a));
        }
    } else if (kind == 21) {
        // Poisson: the upper regularized incomplete gamma at `⌊x⌋ + 1`.
        out = 0.0f32;
        if x >= 0.0f32 {
            out = 1.0f32 - gammainc_p(f32::floor(x) + 1.0f32, a);
        }
    }
    out
}

/// The quantile function of `kind` at `q ∈ (0, 1)`.
///
/// `NaN` where there is no closed form, as in [`cdf_of()`].
pub fn icdf_of(q: f32, a: f32, b: f32, c: f32, nf: NonFinite, kind: u32) -> f32 {
    let mut out: f32 = 0.0;
    out = nf.nan;
    if (Kind::code_has_icdf(kind)) {
        out = closed_form_icdf_of(q, a, b, c, kind);
    }
    out
}

/// [`icdf_of()`] for a kind that has a closed form, and `0` for one that does not.
///
/// Split out so the samplers, which only ever invert kinds that have one, need no
/// [`NonFinite`] to reach it.
pub fn closed_form_icdf_of(q: f32, a: f32, b: f32, c: f32, kind: u32) -> f32 {
    let mut out: f32 = 0.0;
    if (kind == 0) {
        out = a + b * special::std_normal_icdf_f32(q);
    } else if (kind == 1) {
        out = a + q * (b - a);
    } else if (kind == 2) {
        out = -special::log1p_f32(-q) / a;
    } else if (kind == 3) {
        let d = q - 0.5f32;
        out = a - b * special::sign_f32(d) * special::log1p_f32(-2.0f32 * f32::abs(d));
    } else if (kind == 4) {
        out = a + b * f32::tan(special::PI * (q - 0.5f32));
    } else if (kind == 5) {
        out = a - b * f32::ln(-f32::ln(q));
    } else if (kind == 6) {
        out = a * special::SQRT_2 * special::erfinv_f32(q);
    } else if (kind == 7) {
        out = a * f32::tan(0.5f32 * special::PI * q);
    } else if (kind == 8) {
        out = f32::exp(a + b * special::std_normal_icdf_f32(q));
    } else if (kind == 9) {
        out = a * f32::exp(-special::log1p_f32(-q) / b);
    } else if (kind == 10) {
        out = a * f32::powf(-special::log1p_f32(-q), 1.0f32 / b);
    } else if (kind == 11) {
        out = f32::powf(-special::expm1_f32(special::log1p_f32(-q) / b), 1.0f32 / a);
    } else if (kind == 18) {
        // ContinuousBernoulli, PyTorch's closed form with its `p = ½` limit.
        let p = 1.0f32 / (1.0f32 + f32::exp(-a));
        let mut v = q;
        if f32::abs(p - 0.5f32) > 1.0e-3f32 {
            let r = 1.0f32 - p;
            v = (special::log1p_f32(q * (2.0f32 * p - 1.0f32) / r)) / (f32::ln(p) - f32::ln(r));
        }
        out = v.clamp(0.0f32, 1.0f32);
    } else if (kind == 19) {
        out = 0.0f32;
        if q > 1.0f32 / (1.0f32 + f32::exp(a)) {
            out = 1.0f32;
        }
    } else if (kind == 20) {
        out = f32::floor(special::log1p_f32(-q) / special::log_sigmoid_f32(-a));
    }
    out
}

/// The differential (or Shannon) entropy of `kind`.
///
/// `NaN` for the distributions PyTorch leaves unimplemented, plus the three relaxed
/// ones, whose entropies have no elementary closed form. The host layer refuses
/// those before launching.
pub fn entropy_of(a: f32, b: f32, c: f32, nf: NonFinite, kind: u32) -> f32 {
    let mut out: f32 = 0.0;
    out = nf.nan;
    if (kind == 0) {
        out = f32::ln(b) + special::HALF_LN_2PI + 0.5f32;
    } else if (kind == 1) {
        out = f32::ln(b - a);
    } else if (kind == 2) {
        out = 1.0f32 - f32::ln(a);
    } else if (kind == 3) {
        out = 1.0f32 + f32::ln(2.0f32 * b);
    } else if (kind == 4) {
        out = f32::ln(4.0f32 * special::PI * b);
    } else if (kind == 5) {
        out = f32::ln(b) + 1.0f32 + special::EULER_GAMMA;
    } else if (kind == 6) {
        out = f32::ln(a) + special::HALF_LN_2PI + 0.5f32 - special::LN_2;
    } else if (kind == 7) {
        out = f32::ln(2.0f32 * special::PI * a);
    } else if (kind == 8) {
        out = a + f32::ln(b) + special::HALF_LN_2PI + 0.5f32;
    } else if (kind == 9) {
        out = f32::ln(a / b) + 1.0f32 + 1.0f32 / b;
    } else if (kind == 10) {
        out = special::EULER_GAMMA * (1.0f32 - 1.0f32 / b) + f32::ln(a / b) + 1.0f32;
    } else if (kind == 11) {
        // Kumaraswamy: `X^a` is Beta(1, b), which is where the harmonic number
        // `γ + ψ(b+1)` comes from.
        let harmonic = special::EULER_GAMMA + special::digamma_f32(b + 1.0f32);
        out = (1.0f32 - 1.0f32 / b) + (1.0f32 - 1.0f32 / a) * harmonic - f32::ln(a) - f32::ln(b);
    } else if (kind == 12) {
        out = a - f32::ln(b) + special::lgamma_f32(a) + (1.0f32 - a) * special::digamma_f32(a);
    } else if (kind == 13) {
        out = a + f32::ln(b) + special::lgamma_f32(a) - (1.0f32 + a) * special::digamma_f32(a);
    } else if (kind == 14) {
        out = special::lbeta_f32(a, b)
            - (a - 1.0f32) * special::digamma_f32(a)
            - (b - 1.0f32) * special::digamma_f32(b)
            + (a + b - 2.0f32) * special::digamma_f32(a + b);
    } else if (kind == 15) {
        let half = 0.5f32 * a;
        out = (half + 0.5f32) * (special::digamma_f32(half + 0.5f32) - special::digamma_f32(half))
            + 0.5f32 * f32::ln(a)
            + special::lbeta_f32(half, 0.5f32)
            + f32::ln(c);
    } else if (kind == 17) {
        // Von Mises. PyTorch has no entropy for this one; it is two Bessel calls.
        out = f32::ln(2.0f32 * special::PI) + special::log_i0_f32(b)
            - b * special::bessel_ratio_f32(b);
    } else if (kind == 19) {
        let p = 1.0f32 / (1.0f32 + f32::exp(-a));
        out = special::softplus_f32(a) - p * a;
    } else if (kind == 20) {
        // A geometric run is a sequence of Bernoulli trials, and its entropy is the
        // per-trial entropy divided by the probability one ends the run.
        let p = 1.0f32 / (1.0f32 + f32::exp(-a));
        out = (special::softplus_f32(a) - p * a) / p;
    }
    out
}

/// A summary statistic of `kind`: its mean, variance or mode, selected by `which`
/// from [`moment`].
///
/// `NaN` where the statistic does not exist — a Cauchy has no mean, a uniform no
/// mode, a Student's t with one degree of freedom neither — and `+∞` where it
/// diverges, which is a different thing and worth keeping distinct.
// The `if`s below nest a run-time domain test inside a `#[comptime]` arm. Merging
// the two with `&&` would make the arm a run-time branch and lose the pruning that
// is the point of the dispatch.
#[allow(clippy::collapsible_if)]
// Formatted by hand: without its `#[comptime]` markers the host copy of this
// signature fits on one line and rustfmt would join it, and the two copies must
// stay textually identical.
#[rustfmt::skip]
pub fn moment_of(
    a: f32,
    b: f32,
    c: f32,
    nf: NonFinite,
    kind: u32,
    which: u32,
) -> f32 {
    let mut out: f32 = 0.0;
    out = nf.nan;
    if (kind == 0) {
        if (which == 0) {
            out = a;
        } else if (which == 1) {
            out = b * b;
        } else {
            out = a;
        }
    } else if (kind == 1) {
        if (which == 0) {
            out = 0.5f32 * (a + b);
        } else if (which == 1) {
            let w = b - a;
            out = w * w / 12.0f32;
        }
    } else if (kind == 2) {
        if (which == 0) {
            out = 1.0f32 / a;
        } else if (which == 1) {
            out = 1.0f32 / (a * a);
        } else {
            out = 0.0f32;
        }
    } else if (kind == 3) {
        if (which == 0) {
            out = a;
        } else if (which == 1) {
            out = 2.0f32 * b * b;
        } else {
            out = a;
        }
    } else if (kind == 4) {
        if (which == 1) {
            out = nf.inf;
        } else if (which == 2) {
            out = a;
        }
    } else if (kind == 5) {
        if (which == 0) {
            out = a + b * special::EULER_GAMMA;
        } else if (which == 1) {
            out = special::PI * special::PI * b * b / 6.0f32;
        } else {
            out = a;
        }
    } else if (kind == 6) {
        if (which == 0) {
            out = a * f32::sqrt(2.0f32 / special::PI);
        } else if (which == 1) {
            out = a * a * (1.0f32 - 2.0f32 / special::PI);
        } else {
            out = 0.0f32;
        }
    } else if (kind == 7) {
        if (which == 2) {
            out = 0.0f32;
        } else {
            out = nf.inf;
        }
    } else if (kind == 8) {
        let v = b * b;
        if (which == 0) {
            out = f32::exp(a + 0.5f32 * v);
        } else if (which == 1) {
            out = special::expm1_f32(v) * f32::exp(2.0f32 * a + v);
        } else {
            out = f32::exp(a - v);
        }
    } else if (kind == 9) {
        if (which == 0) {
            out = nf.inf;
            if b > 1.0f32 {
                out = a * b / (b - 1.0f32);
            }
        } else if (which == 1) {
            out = nf.inf;
            if b > 2.0f32 {
                let d = b - 1.0f32;
                out = a * a * b / (d * d * (b - 2.0f32));
            }
        } else {
            out = a;
        }
    } else if (kind == 10) {
        let g1 = f32::exp(special::lgamma_f32(1.0f32 + 1.0f32 / b));
        if (which == 0) {
            out = a * g1;
        } else if (which == 1) {
            let g2 = f32::exp(special::lgamma_f32(1.0f32 + 2.0f32 / b));
            out = a * a * (g2 - g1 * g1);
        } else {
            out = 0.0f32;
            if b > 1.0f32 {
                out = a * f32::powf((b - 1.0f32) / b, 1.0f32 / b);
            }
        }
    } else if (kind == 11) {
        // Kumaraswamy's raw moments are Beta functions: `E[Xⁿ] = b·B(1 + n/a, b)`.
        let m1 = f32::exp(f32::ln(b) + special::lbeta_f32(1.0f32 + 1.0f32 / a, b));
        if (which == 0) {
            out = m1;
        } else if (which == 1) {
            let m2 = f32::exp(f32::ln(b) + special::lbeta_f32(1.0f32 + 2.0f32 / a, b));
            out = m2 - m1 * m1;
        } else if a >= 1.0f32 && b >= 1.0f32 {
            out = f32::powf((a - 1.0f32) / (a * b - 1.0f32), 1.0f32 / a);
        }
    } else if (kind == 12) {
        if (which == 0) {
            out = a / b;
        } else if (which == 1) {
            out = a / (b * b);
        } else {
            out = 0.0f32;
            if a >= 1.0f32 {
                out = (a - 1.0f32) / b;
            }
        }
    } else if (kind == 13) {
        if (which == 0) {
            out = nf.inf;
            if a > 1.0f32 {
                out = b / (a - 1.0f32);
            }
        } else if (which == 1) {
            out = nf.inf;
            if a > 2.0f32 {
                let d = a - 1.0f32;
                out = b * b / (d * d * (a - 2.0f32));
            }
        } else {
            out = b / (a + 1.0f32);
        }
    } else if (kind == 14) {
        let total = a + b;
        if (which == 0) {
            out = a / total;
        } else if (which == 1) {
            out = a * b / (total * total * (total + 1.0f32));
        } else if a > 1.0f32 && b > 1.0f32 {
            out = (a - 1.0f32) / (total - 2.0f32);
        }
    } else if (kind == 15) {
        if (which == 0) {
            if a > 1.0f32 {
                out = b;
            }
        } else if (which == 1) {
            if a > 2.0f32 {
                out = c * c * a / (a - 2.0f32);
            } else if a > 1.0f32 {
                out = nf.inf;
            }
        } else {
            out = b;
        }
    } else if (kind == 16) {
        if (which == 0) {
            if b > 2.0f32 {
                out = b / (b - 2.0f32);
            }
        } else if (which == 1) {
            if b > 4.0f32 {
                let d = b - 2.0f32;
                out = 2.0f32 * b * b * (a + b - 2.0f32) / (a * d * d * (b - 4.0f32));
            }
        }
    } else if (kind == 17) {
        if (which == 1) {
            // The circular variance, `1 − I₁(κ)/I₀(κ)`, which is what PyTorch
            // reports and is bounded by one rather than by the line.
            out = 1.0f32 - special::bessel_ratio_f32(b);
        } else {
            out = a;
        }
    } else if (kind == 18) {
        // A continuous Bernoulli is a one-parameter exponential family on `[0, 1]`
        // with natural parameter `t` and log-normaliser `ln((eᵗ − 1)/t)`, so its
        // mean and variance are that function's first two derivatives. Both cancel
        // badly near `t = 0`, where the distribution is uniform; the series below
        // are the Taylor expansions there.
        let t = a;
        if (which == 0) {
            out = cont_bernoulli_mean(t);
        } else if (which == 1) {
            if f32::abs(t) > 0.02f32 {
                let e = special::expm1_f32(t);
                out = 1.0f32 / (t * t) - (e + 1.0f32) / (e * e);
            } else {
                let t2 = t * t;
                out = 1.0f32 / 12.0f32 - t2 * (1.0f32 / 240.0f32 - t2 / 6048.0f32);
            }
        }
    } else if (kind == 19) {
        let p = 1.0f32 / (1.0f32 + f32::exp(-a));
        if (which == 0) {
            out = p;
        } else if (which == 1) {
            out = p * (1.0f32 - p);
        } else {
            out = 0.0f32;
            if a > 0.0f32 {
                out = 1.0f32;
            }
        }
    } else if (kind == 20) {
        // With `p = σ(a)`, the mean `(1−p)/p` is exactly `e^{−a}`.
        let odds = f32::exp(-a);
        if (which == 0) {
            out = odds;
        } else if (which == 1) {
            out = odds * (1.0f32 + odds);
        } else {
            out = 0.0f32;
        }
    } else if (kind == 21) {
        if (which == 2) {
            out = f32::floor(a);
        } else {
            out = a;
        }
    } else if (kind == 22) {
        let p = 1.0f32 / (1.0f32 + f32::exp(-b));
        if (which == 0) {
            out = a * p;
        } else if (which == 1) {
            out = a * p * (1.0f32 - p);
        } else {
            out = f32::floor((a + 1.0f32) * p).clamp(0.0f32, a);
        }
    } else if (kind == 23) {
        let odds = f32::exp(b);
        if (which == 0) {
            out = a * odds;
        } else if (which == 1) {
            out = a * odds * (1.0f32 + odds);
        } else {
            out = 0.0f32;
            if a > 1.0f32 {
                out = f32::floor((a - 1.0f32) * odds);
            }
        }
    }
    out
}

/// One uniform draw in `(0, 1)` for element `index` of stream `stream`.
pub fn uniform_at(
    index: u32,
    index_hi: u32,
    stream: u32,
    key_lo: u32,
    key_hi: u32,
    wide: bool,
) -> f32 {
    rng::unit_open(rng::draw_lane(
        index, index_hi, stream, key_lo, key_hi, wide,
    ))
}

/// A draw from `Gamma(shape, 1)` by Marsaglia and Tsang's squeeze method.
///
/// The idea is that `Gamma(α, 1)` for `α ≥ 1` is a cubed linear function of a
/// standard normal, up to a rejection whose acceptance rate is above 98% for every
/// shape and rises towards one as the shape grows. Shapes below one are handled by
/// Marsaglia's boost: draw from `Gamma(α + 1, 1)` and scale by `U^{1/α}`.
///
/// The `1 − 0.0331 z⁴` test is the published squeeze: it implies the exact
/// condition below it, so taking it changes nothing but the cost — it skips a
/// logarithm on the overwhelming majority of attempts. The two tests are written as
/// separate arms with the same body rather than as one `||` precisely so that the
/// second, and its logarithm, are reached only when the first fails.
#[allow(clippy::if_same_then_else)]
///
/// The loop is capped at [`MAX_TRIES`]. Reaching the cap needs sixty consecutive
/// rejections, which at the *worst* acceptance rate is a probability below `1e-100`;
/// the fallback returns the distribution's own mode, which is at least in the
/// support. The alternative — an unbounded loop — is a kernel that can hang a
/// device that has no way to interrupt it.
pub fn std_gamma_sample(
    shape: f32,
    index: u32,
    index_hi: u32,
    base: u32,
    key_lo: u32,
    key_hi: u32,
    wide: bool,
) -> f32 {
    let mut alpha = shape;
    let mut boost: f32 = 1.0;
    if shape < 1.0f32 {
        alpha = shape + 1.0f32;
        let u = uniform_at(index, index_hi, base + MAX_TRIES, key_lo, key_hi, wide);
        boost = f32::powf(u, 1.0f32 / shape);
    }
    let d = alpha - 1.0f32 / 3.0f32;
    let cc = 1.0f32 / f32::sqrt(9.0f32 * d);
    let mut acc = d;
    let mut i: u32 = 0;
    while i < MAX_TRIES {
        let bits = rng::draw_block(index, index_hi, base + i, key_lo, key_hi, wide);
        let z = special::std_normal_icdf_f32(rng::unit_open(bits.a));
        let u = rng::unit_open(bits.b);
        let root = 1.0f32 + cc * z;
        // Every write to the loop-carried `acc` and `i` goes through a local first;
        // see the module docs on loop-carried assignment.
        let mut next_acc = acc;
        let mut next_i = i + 1u32;
        if root > 0.0f32 {
            let v = root * root * root;
            let z2 = z * z;
            let mut taken: f32 = 0.0;
            if u < 1.0f32 - 0.0331f32 * z2 * z2 {
                taken = 1.0f32;
            } else if f32::ln(u) < 0.5f32 * z2 + d * (1.0f32 - v + f32::ln(v)) {
                taken = 1.0f32;
            }
            if taken > 0.5f32 {
                next_acc = d * v;
                next_i = MAX_TRIES;
            }
        }
        acc = next_acc;
        i = next_i;
    }
    boost * acc
}

/// A draw from `Poisson(rate)`.
///
/// Two algorithms, because no single one is good over the whole range. Below ten,
/// inversion: walk the CDF from zero with a single uniform, which costs one
/// generator call and about `rate` multiplies. Above ten that walk gets long and
/// `exp(−rate)` starts to underflow, so the transformed-rejection method PTRS takes
/// over — the same switch, at the same threshold, that NumPy and PyTorch make.
pub fn poisson_sample(
    rate: f32,
    index: u32,
    index_hi: u32,
    base: u32,
    key_lo: u32,
    key_hi: u32,
    wide: bool,
) -> f32 {
    let mut out: f32 = 0.0;
    if rate < 10.0f32 {
        let u = uniform_at(index, index_hi, base, key_lo, key_hi, wide);
        let mut k: f32 = 0.0;
        let mut term = f32::exp(-rate);
        let mut cum = term;
        let mut i: u32 = 0;
        while i < 200u32 {
            let mut next_k = k;
            let mut next_term = term;
            let mut next_cum = cum;
            let mut next_i = i + 1u32;
            if u > cum {
                next_k = k + 1.0f32;
                next_term = term * rate / next_k;
                next_cum = cum + next_term;
            } else {
                next_i = 200u32;
            }
            k = next_k;
            term = next_term;
            cum = next_cum;
            i = next_i;
        }
        out = k;
    } else {
        // Hörmann's PTRS: a hat made of a triangle in `1/us` whose inverse is
        // closed-form, so a proposal costs two uniforms and no transcendental.
        let bb = 0.931f32 + 2.53f32 * f32::sqrt(rate);
        let aa = 0.02483f32 * bb - 0.059f32;
        let inv_alpha = 1.1239f32 + 1.1328f32 / (bb - 3.4f32);
        let v_r = 0.9277f32 - 3.6224f32 / (bb - 2.0f32);
        let log_rate = f32::ln(rate);
        let mut acc = f32::floor(rate);
        let mut i: u32 = 0;
        while i < MAX_TRIES {
            let bits = rng::draw_block(index, index_hi, base + i, key_lo, key_hi, wide);
            let u = rng::unit_open(bits.a) - 0.5f32;
            let v = rng::unit_open(bits.b);
            let us = 0.5f32 - f32::abs(u);
            let k = f32::floor((2.0f32 * aa / us + bb) * u + rate + 0.43f32);
            let mut taken: f32 = 0.0;
            if us >= 0.07f32 && v <= v_r {
                taken = 1.0f32;
            }
            if taken < 0.5f32 {
                let mut usable: f32 = 1.0;
                if k < 0.0f32 {
                    usable = 0.0f32;
                }
                if us < 0.013f32 && v > us {
                    usable = 0.0f32;
                }
                if usable > 0.5f32 {
                    let hat = f32::ln(v * inv_alpha / (aa / (us * us) + bb));
                    if hat <= k * log_rate - rate - special::lgamma_f32(k + 1.0f32) {
                        taken = 1.0f32;
                    }
                }
            }
            let mut next_acc = acc;
            let mut next_i = i + 1u32;
            if taken > 0.5f32 {
                next_acc = k;
                next_i = MAX_TRIES;
            }
            acc = next_acc;
            i = next_i;
        }
        out = acc;
    }
    out
}

/// A draw from `Binomial(trials, p)`, with `p` given as a logit.
///
/// Inversion while the mean is small, and Hörmann's BTRS above it — the same
/// two-regime split as [`poisson_sample()`] and for the same reason. BTRS is folded
/// about `p = ½` first: its hat is tuned for the smaller of `p` and `1 − p`, so a
/// `p` above a half is sampled as `n` minus a draw at `1 − p`.
///
/// The acceptance test is written as a ratio of exact log-densities against the
/// mode rather than through the Stirling-tail approximation the original paper uses.
/// It costs three `lgamma` calls on the slow path and removes an approximation from
/// a place where an approximation would bias the samples rather than blur them.
pub fn binomial_sample(
    trials: f32,
    logits: f32,
    index: u32,
    index_hi: u32,
    base: u32,
    key_lo: u32,
    key_hi: u32,
    wide: bool,
) -> f32 {
    let raw_p = 1.0f32 / (1.0f32 + f32::exp(-logits));
    let mut p = raw_p;
    let mut flip: f32 = 0.0;
    if raw_p > 0.5f32 {
        p = 1.0f32 - raw_p;
        flip = 1.0f32;
    }
    let n = f32::floor(trials + 0.5f32);
    let q = 1.0f32 - p;
    let mean = n * p;
    let mut draw: f32 = 0.0;
    if mean < 10.0f32 {
        let u = uniform_at(index, index_hi, base, key_lo, key_hi, wide);
        let ratio = p / q;
        let mut k: f32 = 0.0;
        let mut term = f32::exp(n * f32::ln(q));
        let mut cum = term;
        let mut i: u32 = 0;
        while i < 1000u32 {
            let mut next_k = k;
            let mut next_term = term;
            let mut next_cum = cum;
            let mut next_i = i + 1u32;
            if u > cum {
                if k < n {
                    next_k = k + 1.0f32;
                    next_term = term * ratio * (n - k) / next_k;
                    next_cum = cum + next_term;
                } else {
                    next_i = 1000u32;
                }
            } else {
                next_i = 1000u32;
            }
            k = next_k;
            term = next_term;
            cum = next_cum;
            i = next_i;
        }
        draw = k;
    } else {
        let spq = f32::sqrt(mean * q);
        let bb = 1.15f32 + 2.53f32 * spq;
        let aa = 0.0248f32 * bb + 0.01f32 * p - 0.0873f32;
        let centre = mean + 0.5f32;
        let v_r = 0.92f32 - 4.2f32 / bb;
        let alpha = (2.83f32 + 5.1f32 / bb) * spq;
        let ln_p = f32::ln(p);
        let ln_q = f32::ln(q);
        let m = f32::floor((n + 1.0f32) * p);
        // `ln n!` is the same for every attempt, so it comes out of the loop; only
        // the two `k`-dependent log-gammas stay inside.
        let log_trials = special::lgamma_f32(n + 1.0f32);
        let log_mode =
            log_trials - special::lgamma_f32(m + 1.0f32) - special::lgamma_f32(n - m + 1.0f32)
                + m * ln_p
                + (n - m) * ln_q;
        let mut acc = m;
        let mut i: u32 = 0;
        while i < MAX_TRIES {
            let bits = rng::draw_block(index, index_hi, base + i, key_lo, key_hi, wide);
            let u = rng::unit_open(bits.a) - 0.5f32;
            let v = rng::unit_open(bits.b);
            let us = 0.5f32 - f32::abs(u);
            let k = f32::floor((2.0f32 * aa / us + bb) * u + centre);
            let mut usable: f32 = 1.0;
            if k < 0.0f32 {
                usable = 0.0f32;
            }
            if k > n {
                usable = 0.0f32;
            }
            let mut taken: f32 = 0.0;
            if usable > 0.5f32 {
                if us >= 0.07f32 && v <= v_r {
                    taken = 1.0f32;
                }
                if taken < 0.5f32 {
                    let hat = f32::ln(v * alpha / (aa / (us * us) + bb));
                    let target = log_trials
                        - special::lgamma_f32(k + 1.0f32)
                        - special::lgamma_f32(n - k + 1.0f32)
                        + k * ln_p
                        + (n - k) * ln_q
                        - log_mode;
                    if hat <= target {
                        taken = 1.0f32;
                    }
                }
            }
            let mut next_acc = acc;
            let mut next_i = i + 1u32;
            if taken > 0.5f32 {
                next_acc = k;
                next_i = MAX_TRIES;
            }
            acc = next_acc;
            i = next_i;
        }
        draw = acc;
    }
    let mut out = draw;
    if flip > 0.5f32 {
        out = n - draw;
    }
    out
}

/// A draw from `VonMises(0, concentration)`, in `[−π, π)`.
///
/// Best and Fisher's wrapped-Cauchy rejection method, which is what PyTorch uses.
/// The proposal is a wrapped Cauchy tuned so its acceptance rate stays above about
/// 66% for every concentration, and the accepted angle comes out of a single
/// `acos`. Below a concentration of `1e-4` the distribution is uniform to well
/// inside `f32`, and the tuning constants divide by the concentration, so that case
/// is taken directly.
///
/// As in [`std_gamma_sample()`], the two acceptance tests are separate arms with the
/// same body so the second — the one with the logarithm — is only reached when the
/// cheap one fails.
#[allow(clippy::if_same_then_else)]
pub fn von_mises_sample(
    concentration: f32,
    index: u32,
    index_hi: u32,
    base: u32,
    key_lo: u32,
    key_hi: u32,
    wide: bool,
) -> f32 {
    let mut out: f32 = 0.0;
    if concentration < 1.0e-4f32 {
        out = special::PI
            * (2.0f32 * uniform_at(index, index_hi, base, key_lo, key_hi, wide) - 1.0f32);
    } else {
        let tau = 1.0f32 + f32::sqrt(1.0f32 + 4.0f32 * concentration * concentration);
        let rho = (tau - f32::sqrt(2.0f32 * tau)) / (2.0f32 * concentration);
        let r = (1.0f32 + rho * rho) / (2.0f32 * rho);
        let mut acc: f32 = 0.0;
        let mut i: u32 = 0;
        while i < MAX_TRIES {
            let bits = rng::draw_block(index, index_hi, base + i, key_lo, key_hi, wide);
            let u1 = rng::unit_open(bits.a);
            let u2 = rng::unit_open(bits.b);
            let u3 = rng::unit_open(bits.c);
            let z = f32::cos(special::PI * u1);
            let f = (1.0f32 + r * z) / (r + z);
            let cc = concentration * (r - f);
            let mut taken: f32 = 0.0;
            if u2 < cc * (2.0f32 - cc) {
                taken = 1.0f32;
            } else if f32::ln(cc / u2) + 1.0f32 - cc >= 0.0f32 {
                taken = 1.0f32;
            }
            let mut next_acc = acc;
            let mut next_i = i + 1u32;
            if taken > 0.5f32 {
                next_acc = special::sign_f32(u3 - 0.5f32) * f32::acos(f.clamp(-1.0f32, 1.0f32));
                next_i = MAX_TRIES;
            }
            acc = next_acc;
            i = next_i;
        }
        out = acc;
    }
    out
}

/// Wrap an angle into `[−π, π)`.
pub fn wrap_angle(x: f32) -> f32 {
    let two_pi = 2.0f32 * special::PI;
    let shifted = x + special::PI;
    shifted - two_pi * f32::floor(shifted / two_pi) - special::PI
}

/// A draw from `kind` out of one 32-bit word of randomness.
///
/// Split out of [`sample_of()`] so that the scalar path and the four-at-a-time path
/// cannot drift: both call this, and neither knows how the word was produced. Only
/// the families that need exactly one uniform appear here —
/// [`Kind::lane_sampled`] is the list — and every other kind returns zero, which no
/// caller ever sees because the host picks the path.
pub fn sample_from_bits_of(bits: u32, a: f32, b: f32, c: f32, kind: u32) -> f32 {
    let mut out: f32 = 0.0;
    if (kind <= 11) {
        // Everything with an elementary quantile is sampled by inverting it: one
        // uniform, no rejection, and a draw that is a differentiable function of the
        // parameters — which is exactly what makes these the reparameterisable ones.
        out = closed_form_icdf_of(rng::unit_open(bits), a, b, c, kind);
    } else if (kind == 18) {
        out = closed_form_icdf_of(rng::unit_open(bits), a, b, c, kind);
    } else if (kind == 19) {
        // Half-open, so a probability of exactly zero can never produce a one.
        let u = rng::unit_half_open(bits);
        out = 0.0f32;
        if u < 1.0f32 / (1.0f32 + f32::exp(-a)) {
            out = 1.0f32;
        }
    } else if (kind == 20) {
        // `⌊ln U / ln(1 − p)⌋`, with `ln(1 − p)` taken as `log σ(−logit)` so that a
        // `p` near one keeps its digits.
        out = f32::floor(f32::ln(rng::unit_open(bits)) / special::log_sigmoid_f32(-a));
    } else if (kind == 24) {
        let u = rng::unit_open(bits);
        out = (b + f32::ln(u) - special::log1p_f32(-u)) / a;
    } else if (kind == 25) {
        let u = rng::unit_open(bits);
        let y = (b + f32::ln(u) - special::log1p_f32(-u)) / a;
        out = 1.0f32 / (1.0f32 + f32::exp(-y));
    }
    out
}

/// One draw from `kind`, for element `index`.
///
/// The draw depends on `index`, the seed and nothing else — not on how the launch
/// was shaped, not on how many elements were asked for, and not on which other
/// elements a unit happened to also compute. That is what makes a sample bit-exact
/// rather than merely correct in distribution.
pub fn sample_of(
    a: f32,
    b: f32,
    c: f32,
    index: u32,
    index_hi: u32,
    key_lo: u32,
    key_hi: u32,
    kind: u32,
    wide: bool,
) -> f32 {
    let mut out: f32 = 0.0;
    if (kind <= 11) {
        out = sample_from_bits_of(
            rng::draw_lane(index, index_hi, 0u32, key_lo, key_hi, wide),
            a,
            b,
            c,
            kind,
        );
    } else if (kind == 12) {
        out = std_gamma_sample(a, index, index_hi, 0u32, key_lo, key_hi, wide) / b;
    } else if (kind == 13) {
        out = b / std_gamma_sample(a, index, index_hi, 0u32, key_lo, key_hi, wide);
    } else if (kind == 14) {
        // A Beta is the share one of two independent Gammas takes of their sum. The
        // second draws from its own block of streams so the two never correlate.
        let g1 = std_gamma_sample(a, index, index_hi, 0u32, key_lo, key_hi, wide);
        let g2 = std_gamma_sample(b, index, index_hi, SUB_DRAW, key_lo, key_hi, wide);
        out = g1 / (g1 + g2);
    } else if (kind == 15) {
        // Student's t: a normal divided by the root of a scaled chi-square, which is
        // a Gamma of half the degrees of freedom.
        let z =
            special::std_normal_icdf_f32(uniform_at(index, index_hi, 0u32, key_lo, key_hi, wide));
        let g = std_gamma_sample(0.5f32 * a, index, index_hi, SUB_DRAW, key_lo, key_hi, wide);
        out = b + c * z * f32::sqrt(0.5f32 * a / g);
    } else if (kind == 16) {
        let g1 = std_gamma_sample(0.5f32 * a, index, index_hi, 0u32, key_lo, key_hi, wide);
        let g2 = std_gamma_sample(0.5f32 * b, index, index_hi, SUB_DRAW, key_lo, key_hi, wide);
        // Two scaled chi-squares; a chi-square with `k` degrees of freedom is
        // twice a `Gamma(k/2, 1)`, and the twos cancel out of the ratio.
        out = (g1 / (0.5f32 * a)) / (g2 / (0.5f32 * b));
    } else if (kind == 17) {
        out = wrap_angle(a + von_mises_sample(b, index, index_hi, 0u32, key_lo, key_hi, wide));
    } else if (kind == 21) {
        out = poisson_sample(a, index, index_hi, 0u32, key_lo, key_hi, wide);
    } else if (kind == 22) {
        out = binomial_sample(a, b, index, index_hi, 0u32, key_lo, key_hi, wide);
    } else if (kind == 23) {
        // A negative binomial is a Poisson whose rate is itself Gamma-distributed;
        // that mixture *is* the distribution, so this is exact rather than a
        // two-stage approximation.
        let rate = std_gamma_sample(a, index, index_hi, 0u32, key_lo, key_hi, wide) * f32::exp(b);
        out = poisson_sample(rate, index, index_hi, SUB_DRAW, key_lo, key_hi, wide);
    } else {
        out = sample_from_bits_of(
            rng::draw_lane(index, index_hi, 0u32, key_lo, key_hi, wide),
            a,
            b,
            c,
            kind,
        );
    }
    out
}

/// The logistic sigmoid, `σ(t)`.
pub fn sigmoid_f32(t: f32) -> f32 {
    1.0f32 / (1.0f32 + f32::exp(-t))
}

/// Every partial derivative of [`log_prob_of()`], in one pass.
///
/// Hand-derived rather than composed, which is the whole reason this module exists:
/// a normal's `∂ log p/∂σ` written out of differentiable tensor ops is a dozen
/// launches and a dozen intermediates, and written out is `(z² − 1)/σ`.
///
/// Slots a distribution does not use are left at zero, as is `dx` for a discrete
/// distribution whose support is not differentiable in any useful sense — except
/// where the density does extend continuously, which is exactly the case PyTorch's
/// own `log_prob` covers by accepting a non-integer `value`.
pub fn log_prob_grad_of(x: f32, a: f32, b: f32, c: f32, kind: u32) -> Grad4 {
    let mut dx: f32 = 0.0;
    let mut da: f32 = 0.0;
    let mut db: f32 = 0.0;
    let mut dc: f32 = 0.0;
    if (kind == 0) {
        let z = (x - a) / b;
        dx = -z / b;
        da = z / b;
        db = (z * z - 1.0f32) / b;
    } else if (kind == 1) {
        let w = 1.0f32 / (b - a);
        da = w;
        db = -w;
    } else if (kind == 2) {
        dx = -a;
        da = 1.0f32 / a - x;
    } else if (kind == 3) {
        let s = special::sign_f32(x - a) / b;
        dx = -s;
        da = s;
        db = (f32::abs(x - a) / b - 1.0f32) / b;
    } else if (kind == 4) {
        let z = (x - a) / b;
        let g = 2.0f32 * z / (1.0f32 + z * z);
        dx = -g / b;
        da = g / b;
        db = (z * g - 1.0f32) / b;
    } else if (kind == 5) {
        let z = (x - a) / b;
        let g = 1.0f32 - f32::exp(-z);
        dx = -g / b;
        da = g / b;
        db = (z * g - 1.0f32) / b;
    } else if (kind == 6) {
        let z = x / a;
        dx = -z / a;
        da = (z * z - 1.0f32) / a;
    } else if (kind == 7) {
        let z = x / a;
        let g = 2.0f32 * z / (1.0f32 + z * z);
        dx = -g / a;
        da = (z * g - 1.0f32) / a;
    } else if (kind == 8) {
        let l = f32::ln(x);
        let z = (l - a) / b;
        dx = (-z / b - 1.0f32) / x;
        da = z / b;
        db = (z * z - 1.0f32) / b;
    } else if (kind == 9) {
        dx = -(b + 1.0f32) / x;
        da = b / a;
        db = 1.0f32 / b + f32::ln(a) - f32::ln(x);
    } else if (kind == 10) {
        let z = x / a;
        let t = f32::powf(z, b);
        dx = (b - 1.0f32) / x - b * t / x;
        da = b * (t - 1.0f32) / a;
        db = 1.0f32 / b + (1.0f32 - t) * f32::ln(z);
    } else if (kind == 11) {
        let lx = f32::ln(x);
        let w = f32::powf(x, a);
        let rest = 1.0f32 - w;
        dx = (a - 1.0f32) / x - (b - 1.0f32) * a * w / (x * rest);
        da = 1.0f32 / a + lx - (b - 1.0f32) * w * lx / rest;
        db = 1.0f32 / b + special::log1p_f32(-w);
    } else if (kind == 12) {
        dx = (a - 1.0f32) / x - b;
        da = f32::ln(b) + f32::ln(x) - special::digamma_f32(a);
        db = a / b - x;
    } else if (kind == 13) {
        dx = b / (x * x) - (a + 1.0f32) / x;
        da = f32::ln(b) - special::digamma_f32(a) - f32::ln(x);
        db = a / b - 1.0f32 / x;
    } else if (kind == 14) {
        let psi_sum = special::digamma_f32(a + b);
        dx = (a - 1.0f32) / x - (b - 1.0f32) / (1.0f32 - x);
        da = f32::ln(x) - special::digamma_f32(a) + psi_sum;
        db = special::log1p_f32(-x) - special::digamma_f32(b) + psi_sum;
    } else if (kind == 15) {
        let z = (x - b) / c;
        let half = 0.5f32 * a;
        let scaled = z * z / a;
        let sq = 1.0f32 + scaled;
        let slope = (a + 1.0f32) * z / (a * sq);
        dx = -slope / c;
        db = slope / c;
        dc = (slope * z - 1.0f32) / c;
        da = 0.5f32 * (special::digamma_f32(half + 0.5f32) - special::digamma_f32(half))
            - 0.5f32 / a
            - 0.5f32 * special::log1p_f32(scaled)
            + (a + 1.0f32) * scaled / (2.0f32 * a * sq);
    } else if (kind == 16) {
        let h1 = 0.5f32 * a;
        let h2 = 0.5f32 * b;
        let r = a / b;
        let denom = 1.0f32 + r * x;
        let psi_sum = special::digamma_f32(h1 + h2);
        dx = (h1 - 1.0f32) / x - (h1 + h2) * r / denom;
        da = 0.5f32
            * (psi_sum - special::digamma_f32(h1) + f32::ln(r) + 1.0f32 + f32::ln(x)
                - special::log1p_f32(r * x))
            - (h1 + h2) * x / (b * denom);
        db = 0.5f32 * (psi_sum - special::digamma_f32(h2) - special::log1p_f32(r * x)) - h1 / b
            + (h1 + h2) * r * x / (b * denom);
    } else if (kind == 17) {
        let s = f32::sin(x - a);
        dx = -b * s;
        da = b * s;
        db = f32::cos(x - a) - special::bessel_ratio_f32(b);
    } else if (kind == 18) {
        // An exponential family in its natural parameter: the score is the value
        // minus the mean, and nothing else survives.
        dx = a;
        da = x - cont_bernoulli_mean(a);
    } else if (kind == 19) {
        dx = a;
        da = x - sigmoid_f32(a);
    } else if (kind == 20) {
        dx = special::log_sigmoid_f32(-a);
        da = sigmoid_f32(-a) - x * sigmoid_f32(a);
    } else if (kind == 21) {
        dx = f32::ln(a) - special::digamma_f32(x + 1.0f32);
        da = x / a - 1.0f32;
    } else if (kind == 22) {
        dx = b + special::digamma_f32(a - x + 1.0f32) - special::digamma_f32(x + 1.0f32);
        da = special::digamma_f32(a + 1.0f32)
            - special::digamma_f32(a - x + 1.0f32)
            - special::softplus_f32(b);
        db = x - a * sigmoid_f32(b);
    } else if (kind == 23) {
        let psi_sum = special::digamma_f32(a + x);
        dx = special::log_sigmoid_f32(b) + psi_sum - special::digamma_f32(1.0f32 + x);
        da = special::log_sigmoid_f32(-b) + psi_sum - special::digamma_f32(a);
        db = x * sigmoid_f32(-b) - a * sigmoid_f32(b);
    } else if (kind == 24) {
        let diff = b - x * a;
        let g = 1.0f32 - 2.0f32 * sigmoid_f32(diff);
        dx = -a * g;
        da = 1.0f32 / a - x * g;
        db = g;
    } else if (kind == 25) {
        let y = f32::ln(x) - special::log1p_f32(-x);
        let diff = b - y * a;
        let g = 1.0f32 - 2.0f32 * sigmoid_f32(diff);
        dx = -a * g / (x * (1.0f32 - x)) - 1.0f32 / x + 1.0f32 / (1.0f32 - x);
        da = 1.0f32 / a - y * g;
        db = g;
    }
    Grad4 { dx, da, db, dc }
}

/// Every partial derivative of [`entropy_of()`].
///
/// `dx` is always zero — an entropy has no value argument — and the slots of a
/// distribution whose entropy is not implemented are `NaN`, matching [`entropy_of()`]
/// so that a caller cannot silently differentiate something that was never computed.
pub fn entropy_grad_of(a: f32, b: f32, c: f32, nf: NonFinite, kind: u32) -> Grad4 {
    let mut da: f32 = 0.0;
    let mut db: f32 = 0.0;
    let mut dc: f32 = 0.0;
    da = nf.nan;
    db = nf.nan;
    if (kind == 0) {
        da = 0.0f32;
        db = 1.0f32 / b;
    } else if (kind == 1) {
        let w = 1.0f32 / (b - a);
        da = -w;
        db = w;
    } else if (kind == 2) {
        da = -1.0f32 / a;
    } else if (kind == 3 || kind == 4 || kind == 5) {
        // Laplace, Cauchy and Gumbel are location–scale families whose entropy is
        // `ln(scale)` plus a constant, so the location does not enter and the scale
        // enters the same way in all three.
        da = 0.0f32;
        db = 1.0f32 / b;
    } else if (kind == 6 || kind == 7) {
        // Half-normal and half-Cauchy, likewise, with the scale in the first slot.
        da = 1.0f32 / a;
    } else if (kind == 8) {
        da = 1.0f32;
        db = 1.0f32 / b;
    } else if (kind == 9) {
        da = 1.0f32 / a;
        db = -(1.0f32 + 1.0f32 / b) / b;
    } else if (kind == 10) {
        da = 1.0f32 / a;
        db = special::EULER_GAMMA / (b * b) - 1.0f32 / b;
    } else if (kind == 11) {
        let harmonic = special::EULER_GAMMA + special::digamma_f32(b + 1.0f32);
        da = harmonic / (a * a) - 1.0f32 / a;
        db = 1.0f32 / (b * b) + (1.0f32 - 1.0f32 / a) * special::trigamma_f32(b + 1.0f32)
            - 1.0f32 / b;
    } else if (kind == 12) {
        da = 1.0f32 + (1.0f32 - a) * special::trigamma_f32(a);
        db = -1.0f32 / b;
    } else if (kind == 13) {
        da = 1.0f32 - (1.0f32 + a) * special::trigamma_f32(a);
        db = 1.0f32 / b;
    } else if (kind == 14) {
        let tri_sum = special::trigamma_f32(a + b);
        da = (a + b - 2.0f32) * tri_sum - (a - 1.0f32) * special::trigamma_f32(a);
        db = (a + b - 2.0f32) * tri_sum - (b - 1.0f32) * special::trigamma_f32(b);
    } else if (kind == 15) {
        let half = 0.5f32 * a;
        let hi = half + 0.5f32;
        // Differentiating `((ν+1)/2)(ψ((ν+1)/2) − ψ(ν/2)) + ½ln ν + ln B(ν/2, ½)`,
        // the four digammas cancel in pairs and only the trigammas and `1/(2ν)`
        // survive.
        da = 0.25f32 * (a + 1.0f32) * (special::trigamma_f32(hi) - special::trigamma_f32(half))
            + 0.5f32 / a;
        db = 0.0f32;
        dc = 1.0f32 / c;
    } else if (kind == 17) {
        let ratio = special::bessel_ratio_f32(b);
        // `d/dκ ln I₀ = I₁/I₀`, and `d/dκ (κ I₁/I₀)` unwinds through the Bessel
        // recurrence `I₀' = I₁` and `I₁' = I₀ − I₁/κ` into the expression below.
        let dratio = 1.0f32 - ratio * ratio - ratio / b;
        da = 0.0f32;
        db = -b * dratio;
    } else if (kind == 19) {
        let p = sigmoid_f32(a);
        da = -a * p * (1.0f32 - p);
    } else if (kind == 20) {
        let p = sigmoid_f32(a);
        let bern = special::softplus_f32(a) - p * a;
        let dbern = -a * p * (1.0f32 - p);
        da = (dbern * p - bern * p * (1.0f32 - p)) / (p * p);
    }
    Grad4 {
        dx: 0.0f32,
        da,
        db,
        dc,
    }
}

/// Every partial derivative of [`icdf_of()`], in one pass.
///
/// This is what makes a *reparameterised* sample differentiable. A draw from one of
/// the inverse-CDF families is `x = F⁻¹(u; θ)` for a `u` that does not depend on
/// `θ`, so `∂x/∂θ` is exactly this — the path derivative, with no score-function
/// variance in it. [`Kind::reparameterised`] says which kinds are covered; the rest
/// leave every slot at zero, and the host layer refuses to build the node.
pub fn icdf_grad_of(q: f32, a: f32, b: f32, c: f32, kind: u32) -> Grad4 {
    let mut dq: f32 = 0.0;
    let mut da: f32 = 0.0;
    let mut db: f32 = 0.0;
    let mut dc: f32 = 0.0;
    dc = 0.0f32;
    if (kind == 0) {
        let z = special::std_normal_icdf_f32(q);
        da = 1.0f32;
        db = z;
        // `dΦ⁻¹/dq = 1/φ(z)`.
        dq = b * f32::exp(0.5f32 * z * z + special::HALF_LN_2PI);
    } else if (kind == 1) {
        da = 1.0f32 - q;
        db = q;
        dq = b - a;
    } else if (kind == 2) {
        let x = -special::log1p_f32(-q) / a;
        da = -x / a;
        dq = 1.0f32 / (a * (1.0f32 - q));
    } else if (kind == 3) {
        let d = q - 0.5f32;
        da = 1.0f32;
        db = -special::sign_f32(d) * special::log1p_f32(-2.0f32 * f32::abs(d));
        dq = 2.0f32 * b / (1.0f32 - 2.0f32 * f32::abs(d));
    } else if (kind == 4) {
        let t = f32::tan(special::PI * (q - 0.5f32));
        da = 1.0f32;
        db = t;
        dq = b * special::PI * (1.0f32 + t * t);
    } else if (kind == 5) {
        let l = -f32::ln(q);
        da = 1.0f32;
        db = -f32::ln(l);
        dq = b / (l * q);
    } else if (kind == 6) {
        let e = special::erfinv_f32(q);
        da = special::SQRT_2 * e;
        // `d erfinv/dq = (√π/2)·exp(erfinv(q)²)`.
        dq = a * special::SQRT_2 * 0.8862269f32 * f32::exp(e * e);
    } else if (kind == 7) {
        let t = f32::tan(0.5f32 * special::PI * q);
        da = t;
        dq = a * 0.5f32 * special::PI * (1.0f32 + t * t);
    } else if (kind == 8) {
        let z = special::std_normal_icdf_f32(q);
        let x = f32::exp(a + b * z);
        da = x;
        db = x * z;
        dq = x * b * f32::exp(0.5f32 * z * z + special::HALF_LN_2PI);
    } else if (kind == 9) {
        let l = special::log1p_f32(-q);
        let x = a * f32::exp(-l / b);
        da = x / a;
        db = x * l / (b * b);
        dq = x / (b * (1.0f32 - q));
    } else if (kind == 10) {
        let l = -special::log1p_f32(-q);
        let x = a * f32::powf(l, 1.0f32 / b);
        da = x / a;
        db = -x * f32::ln(l) / (b * b);
        dq = x / (b * l * (1.0f32 - q));
    } else if (kind == 11) {
        let l = special::log1p_f32(-q);
        let w = -special::expm1_f32(l / b);
        let x = f32::powf(w, 1.0f32 / a);
        let chain = x / (a * w);
        da = -x * f32::ln(w) / (a * a);
        db = chain * (1.0f32 - w) * l / (b * b);
        dq = chain * (1.0f32 - w) / (b * (1.0f32 - q));
    }
    Grad4 { dx: dq, da, db, dc }
}

/// The path derivative of a draw.
///
/// Re-derives the very uniform the forward pass used from `index` and the key, then
/// differentiates the quantile at it. Nothing has to be saved between the passes:
/// the generator is a pure function of where it is, so the backward pass can ask it
/// the same question and get the same answer.
pub fn rsample_grad_of(
    a: f32,
    b: f32,
    c: f32,
    index: u32,
    index_hi: u32,
    key_lo: u32,
    key_hi: u32,
    kind: u32,
    wide: bool,
) -> Grad4 {
    let mut dq: f32 = 0.0;
    let mut da: f32 = 0.0;
    let mut db: f32 = 0.0;
    let mut dc: f32 = 0.0;
    if (kind <= 11) {
        let u = uniform_at(index, index_hi, 0u32, key_lo, key_hi, wide);
        let g = icdf_grad_of(u, a, b, c, kind);
        dq = g.dx;
        da = g.da;
        db = g.db;
        dc = g.dc;
    } else if (kind == 24) {
        // `(logits + logistic noise)/temperature`: linear in the logit, and inverse
        // in the temperature.
        let u = uniform_at(index, index_hi, 0u32, key_lo, key_hi, wide);
        let y = (b + f32::ln(u) - special::log1p_f32(-u)) / a;
        da = -y / a;
        db = 1.0f32 / a;
    } else if (kind == 25) {
        let u = uniform_at(index, index_hi, 0u32, key_lo, key_hi, wide);
        let y = (b + f32::ln(u) - special::log1p_f32(-u)) / a;
        let s = sigmoid_f32(y);
        let jac = s * (1.0f32 - s);
        da = -jac * y / a;
        db = jac / a;
    }
    // `dx` is the derivative with respect to the underlying uniform, which a caller
    // never differentiates through; it is carried only so the struct is one shape.
    Grad4 { dx: dq, da, db, dc }
}

// <<< shared
