#!/usr/bin/env python3
"""Re-derive the host twins of the device-side distribution math.

    python3 tools/host_twins.py

`src/distributions/special.rs` and `src/distributions/univariate.rs` each carry a
region marked `// >>> shared` … `// <<< shared` that is compiled twice: once by
CubeCL's `#[cube]` macro into device IR, and once by rustc into a plain host
function. The second compilation lives in the `_host.rs` file beside each, and this
script produces it by three textual edits:

  1. drop the lines that are exactly `#[cube]`;
  2. drop every `#[comptime] ` marker, which rustc does not accept on a parameter;
  3. rewrite `comptime!(e)` as `(e)`, turning a compile-time branch into a run-time
     one that takes the same arm.

Nothing else changes, and `distributions_bitexact::host_twin_is_the_same_source`
performs the same three edits and fails if the checked-in files disagree. That test
is the reason to trust the twins; this script is only the convenience that produces
them.
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
START = "// >>> shared\n"
END = "\n// <<< shared"


def shared_region(text):
    start = text.index(START) + len(START)
    return text[start : text.index(END, start)]


def to_host(region):
    lines = [line for line in region.split("\n") if line.strip() != "#[cube]"]
    body = "\n".join(lines).replace("#[comptime] ", "")
    return re.sub(r"comptime!\(", "(", body)


HEADERS = {
    "special": """//! The host compilation of [`super`]'s special functions.
//!
//! **Generated by `tools/host_twins.py`.** This is the marked region of
//! `special.rs` after the edits that script documents, and
//! `distributions_bitexact::host_twin_is_the_same_source` fails if it has drifted.
//! Edit `special.rs`, never this.

#![allow(clippy::excessive_precision, unused_assignments)]

// A glob so the doc comments, which are copied verbatim from the parent and link
// to items there, resolve here as well. The explicit `use` lines below it win.
#[allow(unused_imports)]
pub use super::*;
""",
    "univariate": """//! The host compilation of [`super`]'s distribution mathematics.
//!
//! **Generated by `tools/host_twins.py`.** This is the marked region of
//! `univariate.rs` after the edits that script documents, and
//! `distributions_bitexact::host_twin_is_the_same_source` fails if it has drifted.
//! Edit `univariate.rs`, never this.
//!
//! The `use` lines are the one thing that differs beyond those edits: they aim
//! `rng` and `special` at the host twins, so the shared source resolves to host
//! functions here and to device ones there.

#![allow(clippy::excessive_precision, unused_assignments, unused_parens, unused_variables)]

// A glob for the same reason as in `special_host.rs`; the two explicit `use` lines
// that follow shadow it, which is what points `rng` and `special` at the host twins.
#[allow(unused_imports)]
use super::*;
use super::rng::host as rng;
use super::special::host as special;
""",
}


def main():
    for name in ("special", "univariate"):
        src = os.path.join(ROOT, "src", "distributions", f"{name}.rs")
        dst = os.path.join(ROOT, "src", "distributions", f"{name}_host.rs")
        with open(src) as handle:
            region = shared_region(handle.read())
        with open(dst, "w") as handle:
            handle.write(HEADERS[name] + "\n" + START + to_host(region) + END + "\n")
        print(f"wrote {dst}")


if __name__ == "__main__":
    main()
